#!/bin/bash

. ./parameters $1

aws cloudformation create-stack --stack-name foobar --template-url "$url" --parameters ParameterKey=ServerKey,ParameterValue="${ServerKey}" ParameterKey=ServerParams,ParameterValue="${ServerParams}" ParameterKey=KeyName,ParameterValue=$key

